### ISSUE TITLE
tracking social metrics

### ISSUE THREAD

**Issue by ghost** [acebusters/AIPs#275]
# Bounty
6 months of social metrics documentation, time for a payout...

## Scope
- create spreadsheet to document metrics (one-time task)
- weekly report on metrics in tactical call & monday slack post

## Deliverables
- create google spreadsheet
- metric reports for mar20-sep20

## Funding Circle
**General Circle**

## Bounty Owner/Gardener
@zschavi as **Social Maintainer**

## Gain for the Role
more transparent documentation of social metrics, easy to report upon general tactical call

## Roles
bounty gardener/worker: @zschavi / 320 DAI
bounty reviewer: open / 30 DAI

## Gardener checklist
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by ghost** [comment]
# Deliverables
### Google sheet
https://docs.google.com/spreadsheets/d/1OWvmVsu6SHeWBdWjD6ns_UZsykyHRx2gVQw9kclL1xI/edit#gid=0

### Working hours:
one-time spreadsheet setup - no cost

6 months of metrics (09Mar - 09Sep)
20 reports / 15 minutes per report
20/4 = 5 hours of work = **bounty-size S**

**Comment by ghost** [comment]
## Relevant for Review
**Social Maintainer** was part of the *General Circle* when task was started.
The role is now part of *Meta-Crew Circle*.

Further Bounties for Social Maintainer should be gardened in the new-circle.

**Comment by ghost** [comment]
Bounty was objected, therefore closed.
